---
name: isotovideo
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  schedule:
    runs-on: ubuntu-20.04
    container:
      image: "registry.opensuse.org/devel/openqa/containers-tw/isotovideo:qemu-x86"
    steps:
      - uses: actions/checkout@v2
      - name: Verify the test schedule including wheels
        run: isotovideo QEMU_NO_KVM=1 CASEDIR=. SCHEDULE=tests/wheels/launcher _EXIT_AFTER_SCHEDULE=1
      - name: Reveal error logs
        # Note: The sed strips color escape codes
        run: diff -u <(sed -n 's/\r//;s/^.*scheduling \w* //p' $out | sed -r "s/\x1b\[([0-9]{1,2}(;[0-9]{1,2})*)?m//" ) t/data/test_schedule.out
        if: failure()
      - uses: actions/upload-artifact@v2
        with:
          name: Test results
          path: .
        if: always()
  full:
    runs-on: ubuntu-20.04
    container:
      image: "registry.opensuse.org/devel/openqa/containers-tw/isotovideo:qemu-x86"
    steps:
      - uses: actions/checkout@v2
      - name: install jq
        run: zypper -n in jq
      - name: Run test with wheel
        run: isotovideo QEMU_NO_KVM=1 CASEDIR=. SCHEDULE=tests/wheels/launcher
      - name: fail if any test module failed
        run: jq .result testresults/result-*.json | grep -v ok && echo "Test modules failed" && exit 1
      - name: Reveal error logs
        # Note: The sed strips color escape codes
        run: diff -u <(sed -n 's/\r//;s/^.*scheduling \w* //p' $out | sed -r "s/\x1b\[([0-9]{1,2}(;[0-9]{1,2})*)?m//" ) t/data/test_schedule.out
        if: failure()
      - uses: actions/upload-artifact@v2
        with:
          name: Test results
          path: .
        if: always()
